"use client";

import { useEffect, useState } from "react";
import { createTrack, listTracks, reanalyzeTrack, uploadAudio } from "../lib/api";
import type { TrackWithAnalysis } from "../lib/types";
import { DnaCard } from "./DnaCard";

export default function Home() {
  const [items, setItems] = useState<TrackWithAnalysis[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);

  const [title, setTitle] = useState("");
  const [artist, setArtist] = useState("");
  const [description, setDescription] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const [reanalyzingId, setReanalyzingId] = useState<string | null>(null);
  const [uploadingAudioId, setUploadingAudioId] = useState<string | null>(null);

  async function refresh() {
    try {
      const { items } = await listTracks();
      setItems(items);
      setLoadError(null);
    } catch (err) {
      setLoadError(err instanceof Error ? err.message : "Failed to load tracks.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    refresh();
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    setSubmitError(null);
    try {
      await createTrack({
        title: title.trim(),
        artist: artist.trim(),
        description: description.trim() || undefined,
      });
      setTitle("");
      setArtist("");
      setDescription("");
      await refresh();
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : "Failed to submit track.");
    } finally {
      setSubmitting(false);
    }
  }

  async function handleReanalyze(trackId: string) {
    setReanalyzingId(trackId);
    try {
      await reanalyzeTrack(trackId);
      await refresh();
    } catch (err) {
      setLoadError(err instanceof Error ? err.message : "Failed to re-analyze track.");
    } finally {
      setReanalyzingId(null);
    }
  }

  async function handleUploadAudio(trackId: string, file: File) {
    setUploadingAudioId(trackId);
    try {
      await uploadAudio(trackId, file);
      // Fold the newly measured features into a fresh Song DNA immediately,
      // since that's the whole point of uploading audio, not just storing numbers.
      await reanalyzeTrack(trackId);
      await refresh();
    } catch (err) {
      setLoadError(err instanceof Error ? err.message : "Failed to analyze uploaded audio.");
    } finally {
      setUploadingAudioId(null);
    }
  }

  return (
    <main>
      <h1>Song DNA</h1>
      <p className="subtitle">
        Submit a track&apos;s metadata, and optionally a WAV file, decoded and measured for
        real tempo/energy/brightness, and get a structured, confidence-scored fingerprint:
        genres, moods, and instrumentation, generated by an LLM with a JSON-schema output
        constraint. No LLM key configured? It falls back to a deterministic mock analyzer so
        the whole app still runs end to end.
      </p>

      <form className="panel" onSubmit={handleSubmit}>
        <label>
          Title
          <input value={title} onChange={(e) => setTitle(e.target.value)} required maxLength={200} />
        </label>
        <label>
          Artist
          <input value={artist} onChange={(e) => setArtist(e.target.value)} required maxLength={200} />
        </label>
        <label>
          Description / lyric excerpt (optional)
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            maxLength={4000}
            placeholder="A short description, mood notes, or a lyric excerpt. The more context, the more confident the analysis."
          />
        </label>
        {submitError && <div className="error">{submitError}</div>}
        <button type="submit" disabled={submitting}>
          {submitting ? "Analyzing…" : "Analyze track"}
        </button>
      </form>

      {loading && <div className="empty-state">Loading tracks…</div>}
      {loadError && <div className="error">{loadError}</div>}

      {!loading && items.length === 0 && (
        <div className="empty-state">No tracks yet. Submit one above to get started.</div>
      )}

      {items.map((item) => (
        <DnaCard
          key={item.track.id}
          item={item}
          onReanalyze={handleReanalyze}
          isReanalyzing={reanalyzingId === item.track.id}
          onUploadAudio={handleUploadAudio}
          isUploadingAudio={uploadingAudioId === item.track.id}
        />
      ))}
    </main>
  );
}
