import { createHash } from "node:crypto";
import type { AudioFeatures, SongDna, TrackInput } from "../domain/types.js";
import type { Analyzer } from "./analyzer.js";

const GENRES = [
  "indie folk",
  "synth pop",
  "lo-fi hip hop",
  "alt rock",
  "R&B",
  "electronic",
  "acoustic singer-songwriter",
  "dream pop",
];
const MOODS = [
  "melancholic",
  "uplifting",
  "nostalgic",
  "brooding",
  "triumphant",
  "intimate",
  "restless",
  "warm",
];
const INSTRUMENTS = [
  "acoustic guitar",
  "electric guitar",
  "synth pads",
  "programmed drums",
  "live drum kit",
  "upright bass",
  "strings",
  "piano",
];
const TEMPO_FEELS = ["driving", "laid-back", "frantic", "steady", "swelling"];

function seededIndex(seed: number, salt: number, length: number): number {
  return (seed + salt * 7919) % length;
}

/** Maps a measured tempo to one of the same qualitative labels the hash-based
 * picker uses, so the UI vocabulary stays consistent whether or not audio was
 * uploaded. Naive but grounded in a real measurement rather than a guess. */
function tempoFeelFromBpm(bpm: number): string {
  if (bpm < 80) return "laid-back";
  if (bpm < 110) return "steady";
  if (bpm < 140) return "driving";
  if (bpm < 165) return "swelling";
  return "frantic";
}

/**
 * Deterministic, dependency-free analyzer used whenever no LLM provider is
 * configured (see analysis/index.ts). It derives a stable pseudo-random
 * "fingerprint" from a hash of the track's title + artist, so the same track
 * always produces the same Song DNA (useful for local dev, CI, and demos
 * without burning API credits or requiring secrets). This is intentionally
 * NOT meant to look like a real model output. The `model` field is
 * "mock-v1" everywhere so it's obvious in the UI and in stored rows which
 * rows came from a real LLM analyzer.
 *
 * When real decoded audio features are available, this analyzer grounds its
 * energy and tempo_feel in the measured values instead of the hash. The
 * genre/mood/instrumentation tags are still text-derived guesses (that part
 * genuinely needs an LLM), but energy and tempo stop being fabricated once
 * we've actually measured them from the waveform.
 */
export class MockAnalyzer implements Analyzer {
  readonly modelName = "mock-v1";

  async analyze(track: TrackInput, audio?: AudioFeatures): Promise<SongDna> {
    const hash = createHash("sha256")
      .update(`${track.title}::${track.artist}::${track.description ?? ""}`)
      .digest();
    const seed = hash.readUInt32BE(0);

    const pick = (pool: string[], salt: number, count: number) => {
      const picked: { label: string; confidence: number }[] = [];
      const usedIdx = new Set<number>();
      for (let i = 0; i < count; i++) {
        let idx = seededIndex(seed, salt + i, pool.length);
        while (usedIdx.has(idx)) idx = (idx + 1) % pool.length;
        usedIdx.add(idx);
        const confidence = 0.5 + ((seed >> (i + salt)) % 45) / 100; // 0.50–0.94
        picked.push({ label: pool[idx], confidence: Math.round(confidence * 100) / 100 });
      }
      return picked.sort((a, b) => b.confidence - a.confidence);
    };

    const hashEnergy = Math.round(((seed % 80) / 100 + 0.1) * 100) / 100;
    const hashTempoFeel = TEMPO_FEELS[seededIndex(seed, 3, TEMPO_FEELS.length)];

    const energy = audio ? Math.round(audio.rmsEnergy * 100) / 100 : hashEnergy;
    const tempoFeel = audio?.tempoBpm ? tempoFeelFromBpm(audio.tempoBpm) : hashTempoFeel;

    const genres = pick(GENRES, 1, 2 + (seed % 2));
    const moods = pick(MOODS, 11, 2 + (seed % 2));
    const instrumentation = pick(INSTRUMENTS, 23, 3 + (seed % 3));

    const audioNote = audio
      ? ` Measured from the uploaded audio: ${audio.tempoBpm ? `~${Math.round(audio.tempoBpm)} BPM, ` : ""}` +
        `${Math.round(audio.rmsEnergy * 100)}% energy.`
      : "";

    return {
      genres,
      moods,
      instrumentation,
      tempo_feel: tempoFeel,
      energy,
      summary:
        `"${track.title}" by ${track.artist} reads as ${genres[0].label} with a ` +
        `${moods[0].label} mood, built around ${instrumentation[0].label}.${audioNote} ` +
        `(Generated by the deterministic mock analyzer. Set an LLM provider API key ` +
        `to see real model-driven genre/mood/instrumentation analysis.)`,
    };
  }
}
